### ISSUE TITLE
Skill issue?

### ISSUE THREAD

**Issue by Kowkodivka** [Darkdustry-Coders/DarkdustryPlugin#11]
```
Log.info("[Darkdustry] Начинается инициализация плагина.");
```
Log.infoTag(): _just exists_
```
Log.infoTag("Darkdustry", "Начинается инициализация плагина.")
````

**Comment by Kowkodivka** [comment]
привет дурка <3

**Comment by TheXeony** [comment]
дарк клоун

**Comment by Dyx175** [comment]
дарк клоун

**Comment by LazyCat2** [comment]
дарк клоун

**Comment by osp54** [comment]
дарк клоун

**Comment by wedro023** [comment]
безработный клоун тогда ибо ему не платят 40к

**Comment by TheXeony** [comment]
дарк клоун х2

**Comment by TOP4IK-T4** [comment]
дарк клоун

**Comment by TheXeony** [comment]
считай от 1 до 15 в гитхаб анале, погнали

**Comment by TheXeony** [comment]
1

**Comment by TheXeony** [comment]
@everyone

**Comment by TheXeony** [comment]
<@&944630849071112252>

**Comment by TheXeony** [comment]
2

**Comment by TheXeony** [comment]
3

**Comment by TheXeony** [comment]
4

**Comment by TheXeony** [comment]
5

**Comment by TheXeony** [comment]
6

**Comment by TheXeony** [comment]
7

**Comment by TheXeony** [comment]
8

**Comment by LazyCat2** [comment]
> <@&944630849071112252>

во сколько лет ты узнал, что пинг в эмбедах не работает

**Comment by TheXeony** [comment]
9

**Comment by TheXeony** [comment]
10

**Comment by TheXeony** [comment]
21

**Comment by TheXeony** [comment]
12

**Comment by TheXeony** [comment]
13

**Comment by TheXeony** [comment]
14

**Comment by TheXeony** [comment]
15

**Comment by TheXeony** [comment]
> > <@&944630849071112252>
> 
> во сколько лет ты узнал, что пинг в эмбедах не работает

когда тебе и 3 небыло

**Comment by TheXeony** [comment]
[Слив ююайди дарка](https://youtu.be/xvFZjo5PgG0)

**Comment by LazyCat2** [comment]
> > > <@&944630849071112252>
> > 
> > 
> > во сколько лет ты узнал, что пинг в эмбедах не работает
> 
> когда тебе и 3 небыло

ты как до своего рождения получал знания

**Comment by TheXeony** [comment]
крч, я нашел способ получить админку бесплатно
[Вот](https://youtu.be/xvFZjo5PgG0)

**Comment by Dyx175** [comment]
Дебилы комменты не для этого предназначены

**Comment by LazyCat2** [comment]
> Дебилы комменты не для этого предназначены

всем пофиг

**Comment by Dyx175** [comment]
Сообщения в канале чистят

**Comment by TheXeony** [comment]
[админка](https://youtu.be/xvFZjo5PgG0)

**Comment by TheXeony** [comment]
[админка](https://youtu.be/xvFZjo5PgG0)

**Comment by Dyx175** [comment]
> похуй

**Comment by TheXeony** [comment]
а

**Comment by TheXeony** [comment]
https://images.app.goo.gl/n1RDUGsKqBNt7scd8

**Comment by TheXeony** [comment]
~~~~~~~~~~~~~~а~~~~~~~~~~~~~~

**Comment by LazyCat2** [comment]
> https://images.app.goo.gl/n1RDUGsKqBNt7scd8

спасибо, моя коллекция пополняется
![1 гб котиков, почти 2к файлов](https://cdn.discordapp.com/attachments/1002558414871863316/1003234181704318996/unknown.png)

**Comment by TheEE145** [comment]
дарк клоун

**Comment by Kowkodivka** [comment]
> дарк клоун

skill issue

**Comment by osp54** [comment]
> > дарк клоун
> 
> skill issue

skill issue

**Comment by osp54** [comment]
> > > > дарк клоун
> > > 
> > > 
> > > skill issue
> > 
> > 
> > skill issue
> 
> skill issue?

skill issue.

**Comment by Kowkodivka** [comment]
> > > > > дарк клоун
> > > > 
> > > > 
> > > > skill issue
> > > 
> > > 
> > > skill issue
> > 
> > 
> > skill issue?
> 
> skill issue.

skill issue

**Comment by osp54** [comment]
XD
